<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="4" tests="15" time="158.275">
 <testsuite name="BankAccount page" timestamp="2020-09-18T18:07:43" hostname="localhost" time="67.148" errors="0" tests="3" skipped="0" disabled="0" failures="2">
  <testcase classname="BankAccount page" name="should have correct titles and button text" time="2.581" />
  <testcase classname="BankAccount page" name="should verify credentials" time="2.726" />
  <testcase classname="BankAccount page" name="should redirect to bank account details page" time="61.814">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\844514\App1\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]>
   </failure>
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\844514\App1\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="Home page" timestamp="2020-09-18T18:08:50" hostname="localhost" time="7.543" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="Home page" name="should redirect the user to bank account page" time="3.027" />
  <testcase classname="Home page" name="should redirect the user to mutual fund page" time="2.182" />
  <testcase classname="Home page" name="should redirect the user to transaction page" time="2.331" />
 </testsuite>
 <testsuite name="Login page" timestamp="2020-09-18T18:08:57" hostname="localhost" time="7.942" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="Login page" name="should have correct titles and button text" time="2.066" />
  <testcase classname="Login page" name="should verify credentials" time="2.33" />
  <testcase classname="Login page" name="should redirect the user to the home page if they provided correct credentials" time="3.541" />
 </testsuite>
 <testsuite name="MutualFund page" timestamp="2020-09-18T18:09:05" hostname="localhost" time="9.114" errors="0" tests="3" skipped="0" disabled="0" failures="0">
  <testcase classname="MutualFund page" name="should have correct titles and button text" time="2.437" />
  <testcase classname="MutualFund page" name="should verify credentials" time="2.81" />
  <testcase classname="MutualFund page" name="should redirect to mutual fund details page" time="3.863" />
 </testsuite>
 <testsuite name="Transaction page" timestamp="2020-09-18T18:09:14" hostname="localhost" time="66.528" errors="0" tests="3" skipped="0" disabled="0" failures="2">
  <testcase classname="Transaction page" name="should have correct titles and button text" time="2.128" />
  <testcase classname="Transaction page" name="should verify credentials" time="2.276" />
  <testcase classname="Transaction page" name="should redirect to mutual fund details page" time="62.106">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\844514\App1\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]>
   </failure>
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\844514\App1\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>